
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

// Move the templates from the main file
const PROMPT_STYLES = {
  STEP_BY_STEP: {
    name: "Step-by-Step Instructions",
    template: "I need a step-by-step guide on [TOPIC]. For each step, please:\n1. Explain what to do\n2. Why it's important\n3. Include any warnings or tips\nThe guide should be appropriate for someone with [EXPERIENCE_LEVEL] experience."
  },
  COMPARISON: {
    name: "Comparison Analysis",
    template: "Compare and contrast [ITEM1] and [ITEM2] in terms of:\n- Key features\n- Pros and cons\n- Best use cases\n- Cost considerations\nPlease format your response in a structured way with clear headings and bullet points."
  },
  EXPERT_ROLE: {
    name: "Expert Role Play",
    template: "As an expert in [FIELD], please explain [TOPIC] to me. Include:\n- Key concepts I should understand\n- Common misconceptions\n- Practical applications\nAssume I have [BACKGROUND_LEVEL] background knowledge."
  },
  DECISION_HELP: {
    name: "Decision Helper",
    template: "I'm trying to decide between [OPTION1] and [OPTION2] for [PURPOSE]. My priorities are:\n1. [PRIORITY1]\n2. [PRIORITY2]\n3. [PRIORITY3]\nPlease analyze both options based on these priorities and recommend the best choice with your reasoning."
  },
  ARTICLE_WRITING: {
    name: "Article Content Creation",
    template: "Write a comprehensive article about [TOPIC] for [TARGET_AUDIENCE]. The article should:\n- Have an engaging headline that captures attention\n- Include an introduction that hooks the reader\n- Cover these key points: [KEY_POINT_1], [KEY_POINT_2], [KEY_POINT_3]\n- Be approximately [WORD_COUNT] words\n- Use a [FORMAL/CONVERSATIONAL/EDUCATIONAL] tone\n- Include a call-to-action encouraging readers to [DESIRED_ACTION]\n\nThe article should position our brand as [BRAND_POSITIONING] and align with our value proposition of [VALUE_PROPOSITION]."
  },
  COLD_EMAIL: {
    name: "Cold Email Outreach",
    template: "Write a cold email to [TARGET_PERSONA] at [COMPANY_TYPE] companies. The email should:\n- Have a compelling subject line that achieves [GOAL_OF_SUBJECT_LINE]\n- Open with a personalized hook related to [RECIPIENT_PAIN_POINT/ACHIEVEMENT]\n- Briefly introduce our [PRODUCT/SERVICE] as a solution to [SPECIFIC_PROBLEM]\n- Include 1-2 relevant social proof points or statistics\n- Have a clear, low-friction call-to-action asking for [SPECIFIC_NEXT_STEP]\n- Be under 200 words\n\nThe tone should be [PROFESSIONAL/FRIENDLY/DIRECT] and avoid sounding generic or sales-heavy."
  },
  FOLLOW_UP_EMAIL: {
    name: "Follow-up Email",
    template: "Write a follow-up email to [RECIPIENT_NAME] who [CONTEXT_OF_PREVIOUS_INTERACTION] about [TOPIC/PRODUCT/SERVICE] on [DATE_OF_LAST_CONTACT]. In this follow-up:\n- Reference our previous conversation\n- Provide [NEW_VALUE/INFORMATION] that wasn't covered before\n- Gently remind them about [KEY_BENEFIT] they showed interest in\n- Ask if they've made progress on [DECISION/NEXT_STEP_PREVIOUSLY_DISCUSSED]\n- Suggest a specific next step or offer assistance with [POTENTIAL_OBSTACLE]\n\nKeep the email concise (3-4 short paragraphs) and maintain a [HELPFUL/PROFESSIONAL/FRIENDLY] tone without being pushy."
  },
  SOCIAL_MEDIA_POST: {
    name: "Social Media Content",
    template: "Create a series of [PLATFORM] posts about [TOPIC/PRODUCT/ANNOUNCEMENT] targeting [TARGET_AUDIENCE]. Each post should:\n- Have an attention-grabbing opener\n- Communicate [KEY_MESSAGE] clearly and concisely\n- Include relevant hashtags like [HASHTAG1], [HASHTAG2]\n- End with an engaging question or clear call-to-action\n\nThe posts should align with our brand voice which is [BRAND_VOICE_CHARACTERISTICS] and should be optimized for [PLATFORM]'s best practices. Consider incorporating [TRENDING_TOPIC/CURRENT_EVENT] if relevant."
  },
  PRODUCT_DESCRIPTION: {
    name: "Product Description",
    template: "Write a compelling product description for [PRODUCT_NAME], a [BRIEF_PRODUCT_DESCRIPTION] that helps [TARGET_CUSTOMER] with [PAIN_POINT/NEED]. Include:\n- An attention-grabbing headline\n- 2-3 paragraphs highlighting the key features and benefits\n- Bullet points listing technical specifications: [SPEC1], [SPEC2], [SPEC3]\n- At least three benefit statements that connect features to customer outcomes\n- Social proof element (awards, testimonials, ratings)\n- Clear pricing information and purchase options\n\nThe tone should be [PROFESSIONAL/CONVERSATIONAL/LUXURY/TECHNICAL] and should emphasize our unique selling proposition of [USP]."
  },
  AD_COPY: {
    name: "Advertising Copy",
    template: "Create [PLATFORM] ad copy for our [PRODUCT/SERVICE] targeting [TARGET_AUDIENCE] with [PAIN_POINT/DESIRE]. The ad should:\n- Have a headline under [CHARACTER_LIMIT] characters that creates urgency or curiosity\n- Include [VALUE_PROPOSITION] clearly in the first few lines\n- Highlight [PRIMARY_BENEFIT] and [SECONDARY_BENEFIT]\n- Address common objection: [OBJECTION]\n- End with a clear call-to-action: [CTA]\n\nIncorporate these keywords naturally: [KEYWORD1], [KEYWORD2]. The overall tone should be [URGENT/FRIENDLY/PROFESSIONAL/CONVERSATIONAL] and align with our campaign goal of [CAMPAIGN_GOAL]."
  },
  SALES_PITCH: {
    name: "Sales Pitch Script",
    template: "Create a sales pitch script for [PRODUCT/SERVICE] when speaking with [DECISION_MAKER_TITLE] at [COMPANY_TYPE] companies. The pitch should:\n- Open with a compelling hook about [INDUSTRY_CHALLENGE/TREND]\n- Transition to how our solution addresses [SPECIFIC_PAIN_POINT]\n- Include these key differentiators: [DIFFERENTIATOR1], [DIFFERENTIATOR2]\n- Incorporate customer success story about [SIMILAR_CUSTOMER] who achieved [SPECIFIC_RESULT]\n- Include responses to these common objections: [OBJECTION1], [OBJECTION2]\n- End with a clear next step question that is easy to say yes to\n\nThe pitch should be conversational, last approximately [TIME_LENGTH] minutes, and focus on business outcomes rather than just features."
  },
  CASE_STUDY: {
    name: "Case Study Framework",
    template: "Create an outline for a case study about how [CLIENT_NAME], a [CLIENT_DESCRIPTION], used our [PRODUCT/SERVICE] to solve [PROBLEM/CHALLENGE]. The case study should include:\n- A compelling title that highlights the primary result\n- Company background section (1 paragraph)\n- Challenge section detailing [SPECIFIC_CHALLENGE] and its business impact\n- Solution section explaining why they chose us over [COMPETITOR/ALTERNATIVE] and the implementation process\n- Results section with specific metrics: [METRIC1], [METRIC2], [METRIC3]\n- 1-2 direct quotes from [STAKEHOLDER_TITLE] about the experience\n- Conclusion with future plans or additional benefits discovered\n\nThe tone should be factual and professional while telling a compelling story that similar prospects would relate to."
  },
  NEWSLETTER: {
    name: "Email Newsletter",
    template: "Create an email newsletter for [AUDIENCE_SEGMENT] focused on [NEWSLETTER_THEME]. The newsletter should include:\n- An engaging subject line that promises specific value\n- Personal greeting and brief introduction (2-3 sentences)\n- Main content section covering: [TOPIC1], [TOPIC2], [TOPIC3]\n- A 'featured content' section highlighting [RECENT_ARTICLE/RESOURCE/PRODUCT]\n- An industry insight or tip section providing actionable advice about [RELEVANT_TOPIC]\n- Clear call-to-action for [DESIRED_NEXT_STEP]\n- Brief company news or update section (optional)\n\nThe newsletter should be scannable with clear headings, maintain a [FRIENDLY/PROFESSIONAL/EDUCATIONAL] tone, and provide genuine value while subtly promoting our [PRODUCT/SERVICE/BRAND]."
  },
  // New templates for business owners
  BUSINESS_PLAN: {
    name: "Business Plan Outline",
    template: "Create a comprehensive business plan outline for [BUSINESS_NAME], a [BUSINESS_TYPE] in the [INDUSTRY] industry. The business plan should include:\n\n1. Executive Summary\n- Mission statement: [MISSION_STATEMENT]\n- Key objectives: [OBJECTIVE_1], [OBJECTIVE_2]\n- Basic company information\n\n2. Company Description\n- Business structure: [STRUCTURE_TYPE]\n- Industry background\n- Unique value proposition: [UVP]\n\n3. Market Analysis\n- Target market demographics: [TARGET_CUSTOMER_PROFILE]\n- Market size and growth potential\n- Competitive analysis of [COMPETITOR_1], [COMPETITOR_2]\n\n4. Organization & Management\n- Ownership structure\n- Management team profiles highlighting [KEY_EXPERTISE]\n- Advisory board or consultants (if applicable)\n\n5. Products/Services\n- Detailed description of offerings\n- Pricing strategy\n- Product/service lifecycle\n\n6. Marketing & Sales Strategy\n- Marketing channels: [CHANNEL_1], [CHANNEL_2]\n- Customer acquisition strategy\n- Sales process\n\n7. Financial Projections\n- Startup costs\n- 3-year projections including revenue, expenses, and profit margins\n- Break-even analysis\n\n8. Funding Request (if seeking investment)\n- Amount needed: [AMOUNT]\n- How funding will be used\n- Future financial strategies\n\n9. Appendix\n- Supporting documents\n- Market research data\n- Additional financial information"
  },
  CUSTOMER_SURVEY: {
    name: "Customer Survey/Feedback Request",
    template: "Create a customer feedback survey for [PRODUCT/SERVICE] that will help us improve [SPECIFIC_AREA]. The survey request should:\n\n- Begin with a personalized greeting acknowledging the customer's relationship with our business\n- Clearly explain the purpose of the survey and how their feedback will be used to [SPECIFIC_BENEFIT_TO_CUSTOMER]\n- Include these specific question areas:\n  1. Overall satisfaction with [PRODUCT/SERVICE/EXPERIENCE]\n  2. Specific feedback about [FEATURE/ASPECT] we want to improve\n  3. Likelihood to recommend to others (NPS question)\n  4. Open-ended questions about [SPECIFIC_TOPIC] to gather qualitative insights\n  5. Demographics questions that will help us segment responses\n\n- Mention the survey will take approximately [TIME_ESTIMATE] minutes to complete\n- Offer an incentive of [INCENTIVE] for completing the survey\n- Include a clear deadline of [DATE]\n- End with a sincere thank you and the signature of [SENDER_NAME], [SENDER_POSITION]\n\nThe tone should be [APPRECIATIVE/PROFESSIONAL/FRIENDLY] and emphasize how much we value their input."
  },
  INVESTOR_PITCH: {
    name: "Investor Pitch/Fundraising",
    template: "Create an investor pitch for [COMPANY_NAME], a [COMPANY_DESCRIPTION] seeking [INVESTMENT_AMOUNT] in [FUNDING_ROUND] funding. The pitch should include:\n\n1. The Hook (30 seconds)\n- A compelling opening statement about [PROBLEM] and how we're solving it\n- Our unique value proposition: [UVP]\n\n2. Problem & Solution (2 minutes)\n- Clear articulation of the market problem: [PROBLEM_DETAILS]\n- Our solution: [SOLUTION_OVERVIEW]\n- Why our approach is better than alternatives\n\n3. Market Opportunity (1 minute)\n- Total addressable market size: [TAM_SIZE]\n- Current market trends supporting our growth\n- Our target customer profile: [CUSTOMER_PROFILE]\n\n4. Business Model (1 minute)\n- How we make money: [REVENUE_STREAMS]\n- Current pricing: [PRICING_STRUCTURE]\n- Unit economics: [CAC] customer acquisition cost, [LTV] lifetime value\n\n5. Traction & Validation (2 minutes)\n- Current metrics: [KEY_METRIC_1], [KEY_METRIC_2], [KEY_METRIC_3]\n- Growth rate: [GROWTH_RATE]% [TIMEFRAME]\n- Notable customers or partnerships: [KEY_CUSTOMERS/PARTNERS]\n\n6. Competition & Advantages (1 minute)\n- Key competitors: [COMPETITOR_1], [COMPETITOR_2]\n- Our sustainable competitive advantages: [ADVANTAGE_1], [ADVANTAGE_2]\n\n7. Team (1 minute)\n- Key team members and their relevant experience\n- Why this team is uniquely positioned to win\n\n8. Financial Projections (1 minute)\n- [YEAR_1] through [YEAR_3] revenue projections\n- Path to profitability: [PROFITABILITY_TIMELINE]\n- Use of funds: [USE_1], [USE_2], [USE_3]\n\n9. The Ask (30 seconds)\n- Investment amount: [INVESTMENT_AMOUNT]\n- Valuation: [VALUATION]\n- Key milestones this funding will help us achieve\n\nKeep the entire pitch under 10 minutes, focus on the most compelling data points, and convey confidence in our ability to execute and provide investor returns."
  },
  JOB_DESCRIPTION: {
    name: "Job Description Template",
    template: "Create a compelling job description for a [JOB_TITLE] position at [COMPANY_NAME], a [COMPANY_DESCRIPTION]. The job description should include:\n\n1. Company Overview (2-3 sentences)\n- Brief description of our company and culture\n- Our mission: [COMPANY_MISSION]\n\n2. Position Summary\n- Overview of the role's purpose and how it contributes to company goals\n- Department/team the role belongs to and reporting structure\n- Whether the role is [FULL_TIME/PART_TIME/CONTRACT] and [REMOTE/HYBRID/ON-SITE]\n\n3. Key Responsibilities\n- 5-8 bullet points describing primary duties and accountabilities\n- Specific projects or initiatives the person will own\n- Collaboration expectations with other teams\n\n4. Required Qualifications\n- Education: [EDUCATION_LEVEL] in [FIELD] (if applicable)\n- Experience: [YEARS] years in [SPECIFIC_EXPERIENCE]\n- Technical skills: [SKILL_1], [SKILL_2], [SKILL_3]\n- Certifications: [CERTIFICATION] (if applicable)\n\n5. Preferred Qualifications\n- Additional skills or experience that would be ideal\n- Industry-specific knowledge\n\n6. Personal Attributes\n- Key soft skills needed for success: [SOFT_SKILL_1], [SOFT_SKILL_2]\n- Culture fit characteristics that align with our values\n\n7. Benefits & Perks\n- Salary range: [SALARY_RANGE] (if disclosing)\n- Healthcare and retirement benefits\n- PTO policy highlights\n- Unique perks: [PERK_1], [PERK_2]\n\n8. Diversity & Inclusion Statement\n- Our commitment to building a diverse team\n- Encouragement for underrepresented groups to apply\n\n9. Application Instructions\n- How to apply: [APPLICATION_METHOD]\n- Materials to submit: resume, cover letter, portfolio, etc.\n- Application deadline: [DEADLINE]\n\nThe tone should be professional but reflect our company culture which is [CULTURE_DESCRIPTION]. Avoid unnecessary jargon and focus on what would truly excite qualified candidates about this opportunity."
  },
  PERFORMANCE_REVIEW: {
    name: "Employee Performance Review",
    template: "Create a comprehensive performance review for [EMPLOYEE_NAME], [JOB_TITLE] for the period of [REVIEW_PERIOD]. The review should include:\n\n1. Performance Summary\n- Overall assessment of performance against established goals\n- Key achievements during the review period\n- Areas for development\n\n2. Goal Assessment\n- Goal 1: [GOAL_1_DESCRIPTION]\n  - Results achieved\n  - Metrics/evidence of performance\n  - Rating (Exceeds/Meets/Partially Meets/Does Not Meet)\n\n- Goal 2: [GOAL_2_DESCRIPTION]\n  - Results achieved\n  - Metrics/evidence of performance\n  - Rating\n\n- Goal 3: [GOAL_3_DESCRIPTION]\n  - Results achieved\n  - Metrics/evidence of performance\n  - Rating\n\n3. Core Competency Assessment\n- Technical Skills\n  - Strengths: [TECHNICAL_STRENGTH]\n  - Areas for improvement: [TECHNICAL_IMPROVEMENT_AREA]\n\n- Communication\n  - Strengths: [COMMUNICATION_STRENGTH]\n  - Areas for improvement: [COMMUNICATION_IMPROVEMENT_AREA]\n\n- Teamwork/Collaboration\n  - Strengths: [TEAMWORK_STRENGTH]\n  - Areas for improvement: [TEAMWORK_IMPROVEMENT_AREA]\n\n- Leadership (if applicable)\n  - Strengths: [LEADERSHIP_STRENGTH]\n  - Areas for improvement: [LEADERSHIP_IMPROVEMENT_AREA]\n\n4. Development Plan\n- Specific skills to develop: [SKILL_1], [SKILL_2]\n- Resources/training needed: [RESOURCE_1], [RESOURCE_2]\n- Timeline for improvement: [TIMELINE]\n- How progress will be measured\n\n5. Employee Self-Assessment\n- Space for employee to share their perspective on accomplishments\n- Self-identified areas for growth\n- Career goals and aspirations\n\n6. Manager Feedback\n- Specific examples of effective performance\n- Constructive feedback on areas for improvement\n- Support manager will provide\n\n7. Next Period Goals\n- 3-5 SMART goals for the upcoming review period\n- How these goals align with department/company objectives\n- Metrics that will be used to measure success\n\nThe review should be objective, specific with examples, balanced between recognition and constructive feedback, and forward-looking to support the employee's continued development."
  },
  CRISIS_COMMUNICATION: {
    name: "Crisis Communication",
    template: "Draft a crisis communication response addressing [CRISIS_SITUATION] that has affected [STAKEHOLDERS]. The communication should include:\n\n1. Initial Statement (for immediate release)\n- Clear acknowledgment of the situation\n- Expression of appropriate concern/empathy\n- Immediate actions being taken\n- How stakeholders can get updates or assistance\n\n2. Key Messages (3-5 points that should be consistently communicated)\n- What happened: [BRIEF_FACTUAL_DESCRIPTION]\n- Who is affected and how\n- What we're doing about it\n- Our commitment to resolution and prevention\n\n3. Stakeholder-Specific Messaging\n- For customers/clients: [CUSTOMER_SPECIFIC_MESSAGE]\n- For employees: [EMPLOYEE_SPECIFIC_MESSAGE]\n- For investors/shareholders (if applicable): [INVESTOR_SPECIFIC_MESSAGE]\n- For regulatory bodies (if applicable): [REGULATORY_SPECIFIC_MESSAGE]\n- For the general public/media: [PUBLIC_SPECIFIC_MESSAGE]\n\n4. Q&A Preparation (anticipated questions and responses)\n- Question 1: [ANTICIPATED_QUESTION_1]\n  - Response: [PREPARED_ANSWER_1]\n- Question 2: [ANTICIPATED_QUESTION_2]\n  - Response: [PREPARED_ANSWER_2]\n- Question 3: [ANTICIPATED_QUESTION_3]\n  - Response: [PREPARED_ANSWER_3]\n\n5. Communication Channels\n- Primary channel: [PRIMARY_CHANNEL]\n- Secondary channels: [SECONDARY_CHANNEL_1], [SECONDARY_CHANNEL_2]\n- Frequency of updates: [UPDATE_FREQUENCY]\n\n6. Spokesperson Information\n- Who will serve as the primary spokesperson: [SPOKESPERSON_NAME], [TITLE]\n- Who will serve as backup: [BACKUP_SPOKESPERSON_NAME], [TITLE]\n\nThe tone should be transparent, responsible, empathetic, and solution-focused. Avoid speculation, blame, or promises that cannot be guaranteed. All communications should be reviewed by legal before distribution."
  },
  COMPETITIVE_ANALYSIS: {
    name: "Competitive Analysis",
    template: "Create a comprehensive competitive analysis for [YOUR_COMPANY_NAME] comparing our [PRODUCT/SERVICE] against key competitors in the [INDUSTRY/MARKET_SEGMENT]. The analysis should include:\n\n1. Market Overview\n- Current market size: [MARKET_SIZE]\n- Growth projections: [GROWTH_RATE]% over [TIMEFRAME]\n- Key market trends affecting all competitors\n\n2. Competitor Profiles (repeat for each competitor)\n\nCompetitor 1: [COMPETITOR_1_NAME]\n- Company background and market position\n- Product/service offering compared to ours\n- Target customer segments\n- Pricing strategy: [PRICING_MODEL], [PRICE_RANGE]\n- Key strengths: [STRENGTH_1], [STRENGTH_2]\n- Key weaknesses: [WEAKNESS_1], [WEAKNESS_2]\n- Recent business moves or strategy shifts\n\nCompetitor 2: [COMPETITOR_2_NAME]\n- (Same structure as above)\n\nCompetitor 3: [COMPETITOR_3_NAME]\n- (Same structure as above)\n\n3. Comparative Analysis\n- Features matrix comparing key product/service features\n- Pricing comparison across similar offerings\n- Marketing and distribution approach comparison\n- Customer satisfaction/reviews analysis\n- Market share breakdown\n\n4. SWOT Analysis for Our Company\n- Strengths: [STRENGTH_1], [STRENGTH_2], [STRENGTH_3]\n- Weaknesses: [WEAKNESS_1], [WEAKNESS_2], [WEAKNESS_3]\n- Opportunities: [OPPORTUNITY_1], [OPPORTUNITY_2], [OPPORTUNITY_3]\n- Threats: [THREAT_1], [THREAT_2], [THREAT_3]\n\n5. Strategic Recommendations\n- Unique selling propositions to emphasize\n- Gaps in the market we can exploit\n- Defensive strategies against competitor strengths\n- Specific action items: [ACTION_1], [ACTION_2], [ACTION_3]\n\n6. Monitoring Plan\n- Key metrics to track our competitive position\n- Competitor activities to monitor closely\n- Frequency of competitive analysis updates\n\nThe analysis should be data-driven wherever possible, with sources cited. The tone should be objective and analytical, avoiding subjective assessments unless backed by evidence."
  },
  BUSINESS_PARTNERSHIP: {
    name: "Business Partnership Proposal",
    template: "Create a partnership proposal from [YOUR_COMPANY_NAME] to [POTENTIAL_PARTNER_COMPANY] outlining a strategic collaboration for [PARTNERSHIP_PURPOSE]. The proposal should include:\n\n1. Executive Summary\n- Brief overview of the proposed partnership\n- Core value proposition for both parties\n- Expected timeline and key milestones\n\n2. Company Introductions\n- About [YOUR_COMPANY_NAME]: [YOUR_COMPANY_DESCRIPTION]\n- Why we're interested in partnering with [POTENTIAL_PARTNER_COMPANY]\n- Alignment between our companies' missions and values\n\n3. Partnership Opportunity\n- Market context and opportunity: [MARKET_OPPORTUNITY]\n- Specific collaboration being proposed\n- How this partnership addresses a gap or creates value for both parties\n\n4. Value Exchange\n- What [YOUR_COMPANY_NAME] brings to the partnership: [YOUR_CONTRIBUTION_1], [YOUR_CONTRIBUTION_2]\n- What we're seeking from [POTENTIAL_PARTNER_COMPANY]: [PARTNER_CONTRIBUTION_1], [PARTNER_CONTRIBUTION_2]\n- Unique benefits for [POTENTIAL_PARTNER_COMPANY]: [BENEFIT_1], [BENEFIT_2]\n- Unique benefits for [YOUR_COMPANY_NAME]: [BENEFIT_3], [BENEFIT_4]\n\n5. Partnership Structure\n- Proposed operational model\n- Roles and responsibilities of each party\n- Resource commitments required\n- Revenue/cost sharing model (if applicable)\n\n6. Success Metrics\n- Key performance indicators: [KPI_1], [KPI_2], [KPI_3]\n- How and when we'll measure success\n- Goals for first [TIME_PERIOD]\n\n7. Implementation Roadmap\n- Timeline for partnership launch\n- Key milestones and deadlines\n- Required approvals or agreements\n\n8. About Our Team\n- Key stakeholders from [YOUR_COMPANY_NAME] who will be involved\n- Their relevant experience and roles in the partnership\n\n9. Next Steps\n- Proposed immediate action items\n- Request for meeting/discussion\n- Contact information\n\nThe proposal should be professional, concise, and focus on mutual benefit rather than one-sided gain. Use data points where possible to strengthen the business case, and ensure the tone conveys respect for the potential partner's time and consideration."
  },
  PROJECT_BRIEF: {
    name: "Project Brief",
    template: "Create a project brief for [PROJECT_NAME], a [PROJECT_TYPE] initiative at [COMPANY_NAME]. The brief should include:\n\n1. Project Overview\n- Project name: [PROJECT_NAME]\n- Brief description: [1-2 sentence summary]\n- Project sponsor: [SPONSOR_NAME], [TITLE]\n- Project manager: [PM_NAME], [TITLE]\n\n2. Business Case\n- Problem statement: [PROBLEM/OPPORTUNITY BEING ADDRESSED]\n- Business objectives this project supports\n- Expected business outcomes and benefits\n- How success will be measured\n\n3. Project Scope\n- Key deliverables: [DELIVERABLE_1], [DELIVERABLE_2], [DELIVERABLE_3]\n- What is included in scope\n- What is explicitly out of scope\n- Assumptions and constraints\n\n4. Timeline & Milestones\n- Proposed start date: [START_DATE]\n- Proposed end date: [END_DATE]\n- Key milestones:\n  - [MILESTONE_1]: [DATE_1]\n  - [MILESTONE_2]: [DATE_2]\n  - [MILESTONE_3]: [DATE_3]\n\n5. Budget & Resources\n- Estimated budget: [BUDGET_AMOUNT]\n- Budget breakdown by category: [CATEGORY_1]:[AMOUNT_1], [CATEGORY_2]:[AMOUNT_2]\n- Required resources:\n  - Team members and time commitments\n  - Equipment or materials\n  - External vendors or contractors\n\n6. Stakeholders\n- Key stakeholders and their roles/interests\n- Communication plan (frequency and methods)\n- Decision-making process and approvals required\n\n7. Risks & Mitigations\n- Potential risks: [RISK_1], [RISK_2], [RISK_3]\n- Impact assessment (High/Medium/Low)\n- Mitigation strategies for each risk\n\n8. Success Criteria\n- Specific, measurable criteria that will indicate project success\n- Quality standards that must be met\n- Acceptance process\n\n9. Governance\n- Project team structure\n- Meeting cadence\n- Reporting requirements\n- Change management process\n\nThe brief should be comprehensive yet concise, providing all essential information needed for stakeholders to understand and approve the project."
  },
  SOCIAL_MEDIA_CALENDAR: {
    name: "Social Media Content Calendar",
    template: "Create a [MONTHLY/QUARTERLY] social media content calendar for [COMPANY_NAME] focused on promoting our [PRODUCT/SERVICE/INDUSTRY_EXPERTISE]. The calendar should include:\n\n1. Content Strategy Overview\n- Primary business objectives: [OBJECTIVE_1], [OBJECTIVE_2]\n- Target audiences: [AUDIENCE_1], [AUDIENCE_2]\n- Key messages for this period: [MESSAGE_1], [MESSAGE_2], [MESSAGE_3]\n- Content themes: [THEME_1], [THEME_2], [THEME_3]\n- Voice and tone guidelines\n\n2. Platform Strategy\n- [PLATFORM_1] (e.g., Instagram): [POSTING_FREQUENCY], optimal posting times, content focus\n- [PLATFORM_2] (e.g., LinkedIn): [POSTING_FREQUENCY], optimal posting times, content focus\n- [PLATFORM_3] (e.g., Twitter): [POSTING_FREQUENCY], optimal posting times, content focus\n\n3. Content Categories (with specific post ideas for each)\n- Educational content (how-tos, tips, industry insights):\n  - Post idea 1: [EDUCATIONAL_POST_1]\n  - Post idea 2: [EDUCATIONAL_POST_2]\n\n- Promotional content (product features, offers, launches):\n  - Post idea 1: [PROMOTIONAL_POST_1]\n  - Post idea 2: [PROMOTIONAL_POST_2]\n\n- Engagement content (questions, polls, contests):\n  - Post idea 1: [ENGAGEMENT_POST_1]\n  - Post idea 2: [ENGAGEMENT_POST_2]\n\n- User-generated/testimonial content:\n  - Post idea 1: [UGC_POST_1]\n  - Post idea 2: [UGC_POST_2]\n\n- Behind-the-scenes/culture content:\n  - Post idea 1: [BTS_POST_1]\n  - Post idea 2: [BTS_POST_2]\n\n4. Content Calendar by Week\nWeek 1: [DATE_RANGE]\n- Monday: [PLATFORM] - [POST_TOPIC] - [POST_TYPE]\n- Wednesday: [PLATFORM] - [POST_TOPIC] - [POST_TYPE]\n- Friday: [PLATFORM] - [POST_TOPIC] - [POST_TYPE]\n\nWeek 2: [DATE_RANGE]\n- (Same structure as Week 1)\n\n(Continue for all weeks in the period)\n\n5. Campaign Spotlights\n- Campaign 1: [CAMPAIGN_NAME] - [DATE_RANGE]\n  - Objective and KPIs\n  - Content pieces and platforms\n  - Special considerations\n\n- Campaign 2: [CAMPAIGN_NAME] - [DATE_RANGE]\n  - (Same structure as Campaign 1)\n\n6. Content Creation Requirements\n- Image/video specifications by platform\n- Copy length guidelines\n- Hashtag strategy: [PRIMARY_HASHTAGS], [SECONDARY_HASHTAGS]\n- Call-to-action options\n\n7. Performance Measurement\n- KPIs we'll track: [KPI_1], [KPI_2], [KPI_3]\n- Reporting frequency and method\n- Process for optimizing based on performance\n\nThe calendar should balance promotional and value-add content, align with business goals and audience interests, and maintain a consistent posting schedule while remaining flexible for timely/trending topics."
  }
};

interface PromptTemplatesTabProps {
  onSelectTemplate: (template: string) => void;
}

const PromptTemplatesTab: React.FC<PromptTemplatesTabProps> = ({ onSelectTemplate }) => {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Prompt Templates</CardTitle>
        <CardDescription>
          Use these templates as starting points for common prompt types
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {Object.entries(PROMPT_STYLES).map(([key, { name, template }]) => (
            <Card key={key} className="border">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg">{name}</CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <p className="text-sm bg-slate-50 p-3 rounded mb-3 whitespace-pre-line">{template}</p>
                <Button
                  size="sm"
                  onClick={() => onSelectTemplate(template)}
                  className="w-full"
                >
                  Use This Template
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

export default PromptTemplatesTab;
