// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shzczmrfefedwelplpqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoemN6bXJmZWZlZHdlbHBscHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzcxNDEsImV4cCI6MjA1OTcxMzE0MX0.JKc_EOOFvNM23IY3lJOi6Xmyp-fk8QODWztSOTM5qbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);